{{- $registry := .Values.image.registry -}}
{{- $tag := .Values.image.tag -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels: { app: {{ .Release.Name }}-api }
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels: { app: {{ .Release.Name }}-api }
  template:
    metadata:
      labels: { app: {{ .Release.Name }}-api }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: api
          image: "{{ $registry }}/esar-api:{{ $tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: { name: {{ .Release.Name }}-config }
            - secretRef: { name: {{ .Release.Name }}-secrets }
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /health/live, port: 8080 }
            initialDelaySeconds: 15
          readinessProbe:
            httpGet: { path: /health/ready, port: 8080 }
            initialDelaySeconds: 10
          volumeMounts:
            - name: reports
              mountPath: /data/reports
      volumes:
        - name: reports
          persistentVolumeClaim: { claimName: {{ .Release.Name }}-reports }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-workers
  labels: { app: {{ .Release.Name }}-workers }
spec:
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels: { app: {{ .Release.Name }}-workers }
  template:
    metadata:
      labels: { app: {{ .Release.Name }}-workers }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
        - name: workers
          image: "{{ $registry }}/esar-workers:{{ $tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef: { name: {{ .Release.Name }}-config }
            - secretRef: { name: {{ .Release.Name }}-secrets }
          resources: {{- toYaml .Values.workers.resources | nindent 12 }}
          volumeMounts:
            - name: reports
              mountPath: /data/reports
      volumes:
        - name: reports
          persistentVolumeClaim: { claimName: {{ .Release.Name }}-reports }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels: { app: {{ .Release.Name }}-web }
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels: { app: {{ .Release.Name }}-web }
  template:
    metadata:
      labels: { app: {{ .Release.Name }}-web }
    spec:
      containers:
        - name: web
          image: "{{ $registry }}/esar-web:{{ $tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
